### ISSUE TITLE
Propagate method in python API

### ISSUE THREAD

**Issue by Dimosts** [chocoteam/pychoco#11]
I saw that in the python api we cannot use the propagate function component. One may want to propagate all constraints without search for a solution, as it is described in the docs. Conveniently, in Java we can do it, using the propagate function via the solver. Can this be part of the python API too?

**Comment by cprudhom** [comment]
At first sight, I would say that this requires to provide also two methods :
- `pushLevel()` (or `saveSate()`) 
- `popLevel()` (or `restoreState()`) 
to deal with failures. 

That is not undoable but should be used carefully.

**Comment by dimitri-justeau** [comment]
I agree with Charles, if it's possible in the Java API it should be doable in the Python API, but this is kind of an unusual and advanced usage of a CP solver, so if we add this possibility we should be sure to do it in a way that will not confuse CP beginners.

**Comment by Dimosts** [comment]
Thanks, no rush, was just something I found useful when using in in Java and think that it can be useful also in Python. Not a priority

**Comment by dimitri-justeau** [comment]
Fixed in ee568f93682d1814afcf05e18d3eb69857f5863b

The methods are in the solver API, and named `_propagate`, `_push_state`, and `_pop_state` (I used the underscore character to highlight that these are kind of "private" methods)
