### ISSUE TITLE
time_limit not working properly

### ISSUE THREAD

**Issue by Dimosts** [chocoteam/pychoco#12]
One would expect that the time_limit parameter would be in seconds. However, it seems that it is in nanoseconds, meaning that in order to set a limit to 1 second, you need to specify time_limit = 1000000000.

Besides the fact that this can be confusing to users, it is also not handy as if you set the limit more than 2 seconds, as this is more than the maximum positive integer value that can be represented in 32 bits (i.e., 2147483647), which is the max int value in C and Java.

If I try to specify a limit more than 2147483647, I get the following error:

  File "C:\Users\DTAI\AppData\Roaming\Python\Python310\site-packages\pychoco\backend.py", line 111, in time_counter
    return _backend.time_counter(arg1, arg2)
OverflowError: in method 'time_counter', argument 2 of type 'long'

This makes the time_limit parameter not usable in practice.

**Comment by dimitri-justeau** [comment]
Hi Dimosts,

Thank you for using pychoco and giving us feedbacks, this is exactly what we need to go from this beta version to a first not-beta release :-)

I had seen that there is a problem with the limit_time argument in pychoco (see https://github.com/chocoteam/pychoco/issues/9), and the quick workaround was indeed the limitTime function, which actually takes a string arguments, in which the unit is indicated (e.g. "30s"). In pychoco, you should not use the time_limit argument, but directly call limit_time method on a Solver instance (https://github.com/chocoteam/pychoco/blob/3ee864fa0c1658d5af1528f3cfc057f4d5e43579/pychoco/solver.py#L232).

We'll try to have something more clear and convenient as soon as possible.

**Comment by Dimosts** [comment]
Thank you very much

**Comment by dimitri-justeau** [comment]
Hi Dimosts, yes I will try to do this quickly !
