### ISSUE TITLE
find_all_optimal_solutions bug

### ISSUE THREAD

**Issue by Dimosts** [chocoteam/pychoco#15]
Running find_all_optimal_solutions gives the following error, which is due to a typo

 solutions_list_handle = backend.find_all_optimal_solution(self.handle, objective.handle, maximize, stop)
E       AttributeError: module 'pychoco.backend' has no attribute 'find_all_optimal_solution'. Did you mean: 'find_all_optimal_solutions'?

..\..\..\..\AppData\Roaming\Python\Python310\site-packages\pychoco\solver.py:204: AttributeError

**Comment by dimitri-justeau** [comment]
Fixed in https://github.com/chocoteam/pychoco/commit/4bfb503007541841e88f6a8f6da614176b109346#diff-f5e66ee805e0a068eb3544a721fdd1e8261ab3e2e56c528a37e4c50fd24880fa
