### ISSUE TITLE
update .gitignore

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/pychoco#16]
Hi

Am i wrong to say that some files can be included in the `.gitignore` file ?
For instance:
- pychoco/backend.py
- pychoco/backend_wrap.c
- pychoco/*.so
They are built each time `build.sh` is called and thus should not be parted of comited files.

**Comment by dimitri-justeau** [comment]
Fixed in https://github.com/chocoteam/pychoco/commit/31395f90748e23e9d0ffdc96ff410172c25851c8 and https://github.com/chocoteam/pychoco/commit/c601af148f2e0f86fbdc795dc71770563bdc5d30 . *so files were already ignored.
