### ISSUE TITLE
`model.intvars` with shape ?

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/pychoco#18]
Could this API be useful?

```python
ws = model.intvars((5,6), -1, 1, name="ws")
```

instead of:

```python
ws = [ model.intvars(6, -1, 1, name="ws_"+str(i)) for i in range(5) ]
```

**Comment by dimitri-justeau** [comment]
I guess that the most convenient, and the most consistent with Choco would be creating a `model.intvar_matrix` method, what do you think ?

**Comment by cprudhom** [comment]
I think that the shape version is more pythonic and probably that, if Java allowed this type of declaration we would have adopted it.
That would also reduce the API which is good I think.

**Comment by dimitri-justeau** [comment]
Ok, you conviced me, I'll do this asap
