### ISSUE TITLE
Error in propagation of Increasing and Decreasing global constraints when in negative context

### ISSUE THREAD

**Issue by Dimosts** [chocoteam/pychoco#27]
The increasing and decreasing global constraints are not working properly when used in negative context, in implication and reification. A false value in the bv associated with it does not propagate a false value in the constraint.

I noticed that with the following constraint: increasing(x,y,z) -> p. The constraint is not satisfied in the resulting solution, with"increasing" being true while p being false.

I reduced it to just enforcing ~increasing(x,y,z) (reifying increasing(x,y,z) and then enforcing the bv to false), but it is still satisfied in the solution given.

**Comment by cprudhom** [comment]
Related to https://github.com/chocoteam/choco-solver/issues/1090

**Comment by cprudhom** [comment]
I think this is related to an error in choco-solver.
https://github.com/chocoteam/choco-solver/issues/1093

**Comment by cprudhom** [comment]
That should be fixed in the next release of choco-solver (java).
