### ISSUE TITLE
lex_chain_less accepts a list of intvars but should accept a list of lists of intvars

### ISSUE THREAD

**Issue by Dimosts** [chocoteam/pychoco#30]
Hello,

while trying to use lex_chain_less in the python interface, i get the following error: AttributeError: 'list' object has no attribute 'handle'.

I noticed that this is because in lex_chain_less function, it accepts as input a list of intvars, and then calls make_intvar_array to make a 1d vector.

But, shouldn't it accept a list of lists? In Java, I think it does (https://javadoc.io/doc/org.choco-solver/choco-solver/4.0.3/org/chocosolver/solver/constraints/IIntConstraintFactory.html) although I have not used it myself.

**Comment by cprudhom** [comment]
Can you show the code that crashes?

The following code is working:
```python
m = Model()
ar1 = m.intvars(3, 0, 5)
ar2 = m.intvars(3, -1, 4)
c = m.lex_chain_less(ar1 + ar2)
c.post()
```

**Comment by dimitri-justeau** [comment]
You are right @Dimosts , it was working because in Choco the argument is defined as IntVar[]... , so in the test it was considering a 1 element IntVar[][]. It is now fixed in https://github.com/chocoteam/pychoco/commit/43f33791813ddacfd237a128a77d5d75c5d10eaa
