### ISSUE TITLE
Short Table in python interface (universal value)

### ISSUE THREAD

**Issue by Wout4** [chocoteam/pychoco#31]
From the documentation it looks like using a universal value in a table constraint is not possible through the python interface, but it is in the java interface. Is there a way to do it in python as well?

Kind regards
Wout

**Comment by dimitri-justeau** [comment]
Hi Wout, I think that you are referring to the hybrid table constraint, that was recently introduced in choco-solver. If so, we are currently updating pychoco to choco-solver 4.10.16, so this feature will be available very soon.
